{% set python_min = "3.10" %}
{% set name = "pystac" %}
{% set version = "1.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pystac-{{ version }}.tar.gz
  sha256: 0975f78ac648b89f180378089fdd358006c0dc5d974db57c6f8fa81c4162f5d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - pystac-core >=1.15.0,<2
    - pystac-ext-classification
    - pystac-ext-datacube
    - pystac-ext-eo
    - pystac-ext-file
    - pystac-ext-grid
    - pystac-ext-item-assets
    - pystac-ext-label
    - pystac-ext-mgrs
    - pystac-ext-mlm
    - pystac-ext-pointcloud
    - pystac-ext-projection
    - pystac-ext-raster
    - pystac-ext-render
    - pystac-ext-sar
    - pystac-ext-sat
    - pystac-ext-scientific
    - pystac-ext-storage
    - pystac-ext-table
    - pystac-ext-timestamps
    - pystac-ext-version
    - pystac-ext-view
    - pystac-ext-xarray-assets
    - python >={{ python_min }}
    - python-dateutil >=2.7.0

test:
  imports:
    - pystac
    - pystac.extensions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stac-utils/pystac
  summary: Python library for working with Spatiotemporal Asset Catalog (STAC)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gadomski
    - ocefpaf
